import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description: 'Experience crystal-clear sound with our flagship noise-canceling headphones. Features 40-hour battery life and ergonomic design.',
    price: 299.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    reviews: 1250,
    stock: 15,
  },
  {
    id: '2',
    name: 'Minimalist Leather Watch',
    description: 'A timeless piece for the modern individual. Genuine Italian leather strap with a scratch-resistant sapphire crystal face.',
    price: 189.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800',
    rating: 4.6,
    reviews: 840,
    stock: 25,
  },
  {
    id: '3',
    name: 'Smart Home Assistant',
    description: 'Control your entire home with your voice. Integrated with all major smart devices and features a high-fidelity speaker.',
    price: 129.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1589492477829-5e65395b66cc?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    reviews: 2100,
    stock: 40,
  },
  {
    id: '4',
    name: 'Organic Cotton Hoodie',
    description: 'Sustainable fashion at its best. Made from 100% organic cotton, this hoodie is as comfortable as it is eco-friendly.',
    price: 75.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800',
    rating: 4.5,
    reviews: 560,
    stock: 50,
  },
  {
    id: '5',
    name: 'Professional Camera Lens',
    description: 'Capture stunning details with this 50mm f/1.8 prime lens. Perfect for portraits and low-light photography.',
    price: 450.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    reviews: 320,
    stock: 8,
  },
  {
    id: '6',
    name: 'Ceramic Coffee Set',
    description: 'Handcrafted ceramic set including four mugs and a matching carafe. Elegant matte finish for your morning ritual.',
    price: 89.00,
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
    rating: 4.4,
    reviews: 180,
    stock: 20,
  },
  {
    id: '7',
    name: 'Hydrating Face Serum',
    description: 'Infused with hyaluronic acid and vitamin C, this serum revitalizes your skin for a healthy, glowing complexion.',
    price: 45.00,
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    reviews: 920,
    stock: 100,
  },
  {
    id: '8',
    name: 'Ergonomic Office Chair',
    description: 'Work in comfort with adjustable lumbar support and breathable mesh back. Designed for long hours of productivity.',
    price: 349.00,
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1505797149-43b0076649d6?auto=format&fit=crop&q=80&w=800',
    rating: 4.6,
    reviews: 450,
    stock: 12,
  }
];

export const CATEGORIES: string[] = ['All', 'Electronics', 'Fashion', 'Home', 'Beauty'];
