-- Create the blogs table
CREATE TABLE public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    date TEXT NOT NULL,
    author TEXT NOT NULL,
    img TEXT NOT NULL,
    content JSONB DEFAULT '[]'::jsonb,
    status TEXT DEFAULT 'Published',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;

-- Create policies for public access
CREATE POLICY "Allow public read access" ON public.blogs FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON public.blogs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON public.blogs FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access" ON public.blogs FOR DELETE USING (true);

-- Create a storage bucket for blog images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('blogs', 'blogs', true)
ON CONFLICT (id) DO NOTHING;

-- Set up storage policies for the blogs bucket
CREATE POLICY "Blogs Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'blogs');
CREATE POLICY "Blogs Public Insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'blogs');
CREATE POLICY "Blogs Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'blogs');
CREATE POLICY "Blogs Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'blogs');

-- Insert dummy data
INSERT INTO public.blogs (title, category, date, author, img, status) VALUES
('Lohia College Scholars Making Remarkable Research', 'Research', 'December 9, 2025', 'Howard Esther', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-img1-8-min-1024x614.jpg', 'Published'),
('Strategies for Success in Your First Semester', 'Academics', 'December 9, 2025', 'Howard Esther', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-img1-1-min-1024x614.jpg', 'Published'),
('The Role of Technology in Modern Education', 'Education', 'December 9, 2025', 'Howard Esther', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-img1-3-min-1024x614.jpg', 'Published'),
('Building a Sustainable Future at Lohia College', 'Campus', 'December 9, 2025', 'Howard Esther', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-img1-4-min-1024x614.jpg', 'Published');
