-- Create the donations table
CREATE TABLE public.donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    raised TEXT NOT NULL DEFAULT '₹0',
    goal TEXT NOT NULL,
    img TEXT NOT NULL,
    category TEXT NOT NULL,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (since we are using anon key for admin panel in this setup)
-- In a real production app, you should restrict INSERT/UPDATE/DELETE to authenticated admins only.
CREATE POLICY "Allow public read access" ON public.donations FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON public.donations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON public.donations FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access" ON public.donations FOR DELETE USING (true);
