-- Drop existing table if it exists to allow re-running the script
DROP TABLE IF EXISTS public.events CASCADE;

-- Create the events table
CREATE TABLE public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT NOT NULL,
    month TEXT NOT NULL,
    time TEXT NOT NULL,
    location TEXT NOT NULL,
    description TEXT,
    img TEXT NOT NULL,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (since we are using anon key for admin panel in this setup)
-- In a real production app, you should restrict INSERT/UPDATE/DELETE to authenticated admins only.
CREATE POLICY "Allow public read access" ON public.events FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON public.events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON public.events FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access" ON public.events FOR DELETE USING (true);

-- Create a storage bucket for events images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('events', 'events', true)
ON CONFLICT (id) DO NOTHING;

-- Set up storage policies for the events bucket
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert" ON storage.objects;
DROP POLICY IF EXISTS "Public Update" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'events');
CREATE POLICY "Public Insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'events');
CREATE POLICY "Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'events');
CREATE POLICY "Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'events');

-- Insert dummy data
INSERT INTO public.events (title, date, month, time, location, description, img, link) VALUES
('Dancing to the & Beat of Unity Govt Lohia College..', '07', 'Mar', '09:00 AM - 03:40 PM', 'Churu, RAJ', 'Join us for a spectacular evening of dance and unity at Govt Lohia College. This event will feature performances from various student groups, celebrating our diverse cultural heritage through the universal language of dance. Expect an energetic atmosphere, stunning choreography, and a sense of community that brings us all together.', '/src/assets/first event.webp', '/event-details/1'),
('inter college cricket & tournament-2026..', '08', 'Mar', '09:00 AM - 03:40 PM', 'RAJ, IN', 'Get ready for the most anticipated sports event of the year! The Inter-College Cricket Tournament 2026 brings together the best collegiate teams from across the region to compete for the championship trophy. Come cheer for your college team, enjoy thrilling matches, and experience the spirit of sportsmanship and camaraderie.', '/src/assets/cricekt match.webp', '/event-details/2'),
('Annual Cultural Fest & Talent Showcase 2026..', '15', 'Mar', '10:00 AM - 05:00 PM', 'Main Campus', 'Our Annual Cultural Fest is back, bigger and better than ever! This day-long event is a vibrant showcase of student talent, featuring music, dance, drama, art exhibitions, and culinary delights. It is a wonderful opportunity for students to express their creativity, learn from one another, and celebrate the rich cultural tapestry of our campus community.', '/src/assets/campus-life.png', '/event-details/3'),
('Academic Excellence & Intellectual Development..', '04', 'Aug', '09:00 AM - 03:40 PM', 'MIOT, USA', 'The Academic Excellence & Intellectual Development Summit 2025 brings together educators, researchers, academic leaders, and policymakers to explore strategies for strengthening scholarly quality and intellectual growth in higher education. The summit will focus on innovation in teaching and learning, research excellence, critical thinking, and institutional development to prepare learners for an evolving global knowledge economy.', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/12/e-event-img-1-min-768x461.jpg', '/event-details/4'),
('Innovative Research & Scientific Advancement..', '04', 'Aug', '09:00 AM - 03:40 PM', 'ICL, UK', 'This conference focuses on the latest breakthroughs in scientific research and technological innovation. Leading scientists, researchers, and industry experts will present their findings, discuss emerging trends, and explore collaborative opportunities. Topics will range from artificial intelligence and biotechnology to sustainable energy solutions and advanced materials.', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/12/e-event-img-2-min.jpg', '/event-details/5'),
('Global Education & Cultural Exchange Summit..', '04', 'Aug', '09:00 AM - 03:40 PM', 'MIT, USA', 'The Global Education & Cultural Exchange Summit aims to foster international understanding and collaboration in higher education. Participants will engage in discussions on global citizenship, cross-cultural communication, and the benefits of international exchange programs. The summit will also feature presentations on successful models of global education and strategies for building inclusive and diverse academic communities.', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/12/e-event-img-3-min.jpg', '/event-details/6');
