-- Create the faculty table
CREATE TABLE public.faculty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    img TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.faculty ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (since we are using anon key for admin panel in this setup)
CREATE POLICY "Allow public read access" ON public.faculty FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON public.faculty FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON public.faculty FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access" ON public.faculty FOR DELETE USING (true);

-- Create a storage bucket for faculty images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('faculty', 'faculty', true)
ON CONFLICT (id) DO NOTHING;

-- Set up storage policies for the faculty bucket
CREATE POLICY "Faculty Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'faculty');
CREATE POLICY "Faculty Public Insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'faculty');
CREATE POLICY "Faculty Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'faculty');
CREATE POLICY "Faculty Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'faculty');

-- Insert dummy data
INSERT INTO public.faculty (name, role, img) VALUES
('Priya Sharma', 'Support Teacher', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-6-min.jpg'),
('Rahul Verma', 'Senior Professor', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-1-min.jpg'),
('Amit Patel', 'Assistant Teacher', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-2-min.jpg'),
('Bishal Roy', 'Math Professor', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-3-min.jpg'),
('Mst. Rokeya', 'English Teacher', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-4-min.jpg'),
('Sabbir Ahmed', 'Science Professor', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-5-min.jpg');
