-- Create the faculty table
CREATE TABLE IF NOT EXISTS public.faculty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    img TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.faculty ENABLE ROW LEVEL SECURITY;

-- Create policies for public access
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'faculty' AND policyname = 'Allow public read access') THEN
        CREATE POLICY "Allow public read access" ON public.faculty FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'faculty' AND policyname = 'Allow public insert access') THEN
        CREATE POLICY "Allow public insert access" ON public.faculty FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'faculty' AND policyname = 'Allow public update access') THEN
        CREATE POLICY "Allow public update access" ON public.faculty FOR UPDATE USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'faculty' AND policyname = 'Allow public delete access') THEN
        CREATE POLICY "Allow public delete access" ON public.faculty FOR DELETE USING (true);
    END IF;
END $$;

-- Create a storage bucket for faculty images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('faculty', 'faculty', true)
ON CONFLICT (id) DO NOTHING;

-- Set up storage policies for the faculty bucket
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Faculty Public Access') THEN
        CREATE POLICY "Faculty Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'faculty');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Faculty Public Insert') THEN
        CREATE POLICY "Faculty Public Insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'faculty');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Faculty Public Update') THEN
        CREATE POLICY "Faculty Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'faculty');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Faculty Public Delete') THEN
        CREATE POLICY "Faculty Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'faculty');
    END IF;
END $$;

-- Insert dummy data if empty
INSERT INTO public.faculty (name, role, img)
SELECT 'Priya Sharma', 'Support Teacher', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-6-min.jpg'
WHERE NOT EXISTS (SELECT 1 FROM public.faculty LIMIT 1);

INSERT INTO public.faculty (name, role, img)
SELECT 'Rahul Verma', 'Senior Professor', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-1-min.jpg'
WHERE NOT EXISTS (SELECT 1 FROM public.faculty WHERE name = 'Rahul Verma');

INSERT INTO public.faculty (name, role, img)
SELECT 'Amit Patel', 'Assistant Teacher', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-2-min.jpg'
WHERE NOT EXISTS (SELECT 1 FROM public.faculty WHERE name = 'Amit Patel');

INSERT INTO public.faculty (name, role, img)
SELECT 'Bishal Roy', 'Math Professor', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-3-min.jpg'
WHERE NOT EXISTS (SELECT 1 FROM public.faculty WHERE name = 'Bishal Roy');

INSERT INTO public.faculty (name, role, img)
SELECT 'Mst. Rokeya', 'English Teacher', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-4-min.jpg'
WHERE NOT EXISTS (SELECT 1 FROM public.faculty WHERE name = 'Mst. Rokeya');

INSERT INTO public.faculty (name, role, img)
SELECT 'Sabbir Ahmed', 'Science Professor', 'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-team-5-min.jpg'
WHERE NOT EXISTS (SELECT 1 FROM public.faculty WHERE name = 'Sabbir Ahmed');


-- Create the blogs table
CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    date TEXT NOT NULL,
    author TEXT NOT NULL,
    image TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Published',
    content JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;

-- Create policies for public access
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'blogs' AND policyname = 'Allow public read access') THEN
        CREATE POLICY "Allow public read access" ON public.blogs FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'blogs' AND policyname = 'Allow public insert access') THEN
        CREATE POLICY "Allow public insert access" ON public.blogs FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'blogs' AND policyname = 'Allow public update access') THEN
        CREATE POLICY "Allow public update access" ON public.blogs FOR UPDATE USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'blogs' AND policyname = 'Allow public delete access') THEN
        CREATE POLICY "Allow public delete access" ON public.blogs FOR DELETE USING (true);
    END IF;
END $$;

-- Create a storage bucket for blogs images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('blogs', 'blogs', true)
ON CONFLICT (id) DO NOTHING;

-- Set up storage policies for the blogs bucket
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Blogs Public Access') THEN
        CREATE POLICY "Blogs Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'blogs');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Blogs Public Insert') THEN
        CREATE POLICY "Blogs Public Insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'blogs');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Blogs Public Update') THEN
        CREATE POLICY "Blogs Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'blogs');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Blogs Public Delete') THEN
        CREATE POLICY "Blogs Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'blogs');
    END IF;
END $$;

-- Insert dummy data if empty
INSERT INTO public.blogs (title, category, date, author, image, status, content)
SELECT 
  'Smarter Thinking for Smarter Business Solutions', 
  'Education', 
  'November 26, 2025', 
  'Howard Esther', 
  'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-img1-8-min.jpg', 
  'Published',
  '[{"id": 1, "type": "paragraph", "content": "Education goes beyond textbooks and classrooms. We believe in empowering students to explore their passions challenge conventions."}]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.blogs LIMIT 1);

INSERT INTO public.blogs (title, category, date, author, image, status, content)
SELECT 
  'The Impact of Collaborative Research', 
  'Research', 
  'December 10, 2025', 
  'Sarah Jenkins', 
  'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-img1-9-min.jpg', 
  'Published',
  '[{"id": 1, "type": "paragraph", "content": "Collaborative research brings together diverse minds to solve complex problems."}]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.blogs WHERE title = 'The Impact of Collaborative Research');

INSERT INTO public.blogs (title, category, date, author, image, status, content)
SELECT 
  'Navigating Campus Life: A Guide for Freshmen', 
  'Campus Life', 
  'January 15, 2026', 
  'Michael Chang', 
  'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-img1-10-min.jpg', 
  'Published',
  '[{"id": 1, "type": "paragraph", "content": "Starting university can be daunting, but with the right guidance, it becomes an exciting journey."}]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.blogs WHERE title = 'Navigating Campus Life: A Guide for Freshmen');

INSERT INTO public.blogs (title, category, date, author, image, status, content)
SELECT 
  'Future of Technology in Education', 
  'Innovation', 
  'February 5, 2026', 
  'Dr. Emily Chen', 
  'https://univet.rstheme.com/cyan/wp-content/uploads/sites/17/2025/11/e-bl-img1-11-min.jpg', 
  'Published',
  '[{"id": 1, "type": "paragraph", "content": "Technology is rapidly transforming how we learn and teach."}]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.blogs WHERE title = 'Future of Technology in Education');
